WIP
yldio/asap-hub pull request #1149
Opened 2021-11-15 13:17 UTC by ana-yldio

2021-11-24 17:05 UTC, kmaid requested changes

2021-11-24 17:05 UTC, kmaid commented on apps/frontend/src/structure/ErrorBoundary.tsx
> +    wrapper?: 'ReactErrorBoundary' | 'SentryErrorBoundary';
```suggestion
    sentryReporting?: boolean;
```

2021-11-24 17:07 UTC, jhonny-m approved these changes

2021-11-25 10:39 UTC, kmaid approved these changes

2021-11-25 11:07 UTC, merged