chore: add mock server tests to user controller
yldio/asap-hub pull request #1198
Opened 2021-12-08 14:46 UTC by peterstarling

https://trello.com/c/CeH5RrUB/1748-use-mock-server-for-testing-all-controllers

2021-12-13 19:38 UTC, niezgoda approved these changes

2021-12-14 10:40 UTC, markcsims requested changes

2021-12-14 10:40 UTC, markcsims commented on apps/asap-server/src/handlers/webhooks/webhook-sync-orcid.ts
> +    const squidexGraphqlClientMock = new SquidexGraphql();
This is a real client, not a mock? I think we need to remove the suffix.

2021-12-14 10:40 UTC, markcsims commented on apps/asap-server/src/handlers/webhooks/webhook-connect-by-code.ts
> +    const squidexGraphqlClientMock = new SquidexGraphql();
This is a real client, not a mock? I think we need to remove the suffix.

2021-12-14 11:24 UTC, markcsims approved these changes

2021-12-14 12:55 UTC, merged