fix: group members ui
yldio/asap-hub pull request #1239
Opened 2021-12-17 13:08 UTC by ana-yldio

https://trello.com/c/rV11LRwM/1778-labs-are-showing-on-group-pages-members-component

2021-12-20 10:10 UTC, niezgoda approved these changes

2021-12-21 10:11 UTC, niezgoda approved these changes

2021-12-21 10:47 UTC, kmaid requested changes

2021-12-21 10:47 UTC, kmaid commented on packages/react-components/src/molecules/MembersList.tsx
> +                labStyles(!labsList.length),
```suggestion
              !!labsList.length && labStyles,
```

2021-12-21 10:47 UTC, kmaid commented on packages/react-components/src/molecules/MembersList.tsx
> +  });
```suggestion
const labStyles = css({
    padding: `0 0 ${24 / perRem}em`,
  });
```

2021-12-21 10:47 UTC, kmaid commented on packages/react-components/src/molecules/MembersList.tsx
> +                labStyles(!labsList.length),
This should be more readable

2021-12-21 10:47 UTC, kmaid commented on packages/react-components/src/organisms/GroupMembersSection.tsx
> +          teams: user.teams,
```suggestion
          members={leaders.map(({ user: { labs, ...user}, role }) => ({
          			...user,
          			role
```

2021-12-21 12:43 UTC, closed without merging