Feat/1822 Create Squidex availability metric
yldio/asap-hub pull request #1268
Opened 2022-01-10 10:23 UTC by niezgoda

We want to create metric for when squidex responds with: 

- 5XX 
- 4XX
- GraphQL errors

## Requirements

- have a visual representation of squidex downtime (see list above) along with duration and frequency

2022-01-19 16:50 UTC, kmaid requested changes

2022-01-19 16:50 UTC, kmaid commented on apps/asap-server/src/autogenerated-gql/graphql.ts
>    /** Attention: Check if this user needs to be added to Smart Simple */
Why is this in this PR

2022-01-19 17:30 UTC, niezgoda commented on apps/asap-server/src/autogenerated-gql/graphql.ts
>    /** Attention: Check if this user needs to be added to Smart Simple */
ask Piotr :D

2022-01-20 08:34 UTC, peterstarling requested changes
As I mentioned to your earlier - I think the dashboard definition should be part of the sls config and should be applied to all environments, it can be easily imported especially since our sls config is a ts file. 

You mentioned some limits though? If there is a limit it can be applied conditionally to dev and prod only

2022-02-15 08:19 UTC, peterstarling commented
@niezgoda are we closing this?

2022-02-16 14:13 UTC, closed without merging