CRN-620 remove old research output index
yldio/asap-hub pull request #1350
Opened 2022-02-18 10:50 UTC by marot

2022-02-21 08:22 UTC, peterstarling approved these changes
@marot you might want to consider renaming the -v2 prod and dev sync (simply drop the `v2` suffx). 

Also I would recommend that you clone the current prod and dev index. Once you do that we should run the sync on both and make sure it still works as normal. If something goes wrong we can rename the indexes until we revert so its not a big deal

2022-02-21 08:43 UTC, marot commented
@peterstarling To be sure, I should duplicate/clone the indexes, merge the PR, run the migration, and if there is a problem delete the new prod/dev indexes and rename the duplicated on back to prod/dev, right?

2022-02-21 11:16 UTC, marot commented
@peterstarling after thinking a little about it, I'd prefer to keep the v2 suffix for a little bit. (So that it is clear what workflow is being triggered in the github actions) Otherwise the bahaviour of the workflow might differ depending on what branch you select - when triggering actions manually)

2022-02-22 12:21 UTC, niezgoda requested changes

2022-02-22 12:21 UTC, niezgoda commented on .github/workflows/algolia-sync-v2.yml
> +          ENTITY_TYPE: ${{ (inputs.entity == 'users' && 'user') || (inputs.entity == 'research-outputs' && 'research-output') || 'external-author' }}
`${{ (inputs.entity == 'users' && 'user') || (inputs.entity == 'research-outputs' && 'research-output') || (inputs.entity == 'external-authors' && 'external-author') }}`

2022-02-23 10:45 UTC, merged