Added speakers list component to EventPage
yldio/asap-hub pull request #1566
Opened 2022-05-09 13:32 UTC by oratiu

Created a Speakers List component that gets included in the EventPage as per the requirements in this ticket:
https://asaphub.atlassian.net/jira/software/c/projects/CRN/boards/6?modal=detail&selectedIssue=CRN-a

2022-05-09 13:35 UTC, oratiu commented on packages/react-components/src/organisms/SpeakersList.tsx
> +  [`&:nth-of-type(n+6)`]: {
Same here

2022-05-10 13:00 UTC, markcsims commented on packages/react-components/src/organisms/__tests__/SpeakerList.test.tsx
> +});
I couldn't see tests for the 'user was not announced' functionality

2022-05-10 15:12 UTC, markcsims requested changes

2022-05-10 15:12 UTC, markcsims commented on packages/react-components/src/organisms/SpeakersList.tsx
> +              </Link>
check link has the correct displayName and Id.

Here team has a ? at the end, I don't think this is necessary

2022-05-10 15:12 UTC, markcsims commented on packages/react-components/src/organisms/SpeakersList.tsx
> +          <div key={team.id + user?.id} css={speakerListStyles}>
This isn't unique. What happens if a team has 2 unknown users.

Maybe use the index (and avoid the +)

2022-05-10 15:12 UTC, markcsims commented on packages/react-components/src/organisms/__tests__/SpeakerList.test.tsx
> +});
We seem to be quite light on test coverage. 

The fixtures should be simplified to contain only the basics. We can then extend to test further with expectations and test descriptions explaining what we are testing.

2022-05-12 09:41 UTC, kmaid commented on packages/react-components/src/organisms/SpeakersList.tsx
> +const getPlaceholderAvatarUrl = () =>
I don't think you need to do this. Wont just {userPlaceholderIcon} work

2022-05-12 09:58 UTC, kmaid commented on packages/react-components/src/organisms/__tests__/SpeakerList.test.tsx
> +        speakers: [{ ...announcedSpeaker }],
Don't think you need the spread

2022-05-12 09:59 UTC, kmaid commented on packages/react-components/src/templates/EventPage.tsx
> +        {props.speakers && <SpeakerList {...props} />}
What happens if speakers is an empty array? I think the SpeakerList should be omitted

2022-05-12 10:08 UTC, kmaid commented on packages/react-components/src/organisms/SpeakersList.tsx
> +                      user && network({}).users({}).user({ userId: user?.id }).$
Not sure why we have a ? in user.id and what happens for external users who don't have a profile

2022-05-12 10:49 UTC, kmaid commented on apps/storybook/src/SpeakersList.stories.tsx
> +export const Normal = () => <SpeakersList {...createEventResponse()} />;
Could this be more configurable so I can easily test different scenarios?

2022-05-12 11:42 UTC, kmaid commented on packages/react-components/src/organisms/SpeakersList.tsx
> +    paddingBottom: `${20 / perRem}em`,
This isn't divisible by 3

2022-05-12 14:10 UTC, kmaid commented on packages/react-components/src/templates/EventPage.tsx
> +        {props.speakers.length > 0 && <SpeakerList {...props} />}
```suggestion
        {props.speakers.length && <SpeakerList {...props} />}
```

2022-05-12 14:12 UTC, kmaid commented on packages/validation/src/user-guards.ts
> +  user: EventSpeakerUser | undefined,
Urgh, this is a weird type. I would have expected two types one InternalEventSpeaker one ExternalSpeaker.

2022-05-12 14:14 UTC, kmaid commented on packages/react-components/src/organisms/SpeakersList.tsx
> +                      ? user?.avatarUrl || ''
```suggestion
                      ? user?.avatarUrl 
```
Wouldn't this work?

2022-05-12 14:15 UTC, kmaid commented on packages/react-components/src/organisms/SpeakersList.tsx
> +                      user && network({}).users({}).user({ userId: user.id }).$
```suggestion
				network({}).users({}).user({ userId: user.id }).$
```
?

2022-05-12 14:15 UTC, kmaid commented on packages/react-components/src/organisms/SpeakersList.tsx
> +                      user && network({}).users({}).user({ userId: user.id }).$
```suggestion
                      network({}).users({}).user({ userId: user.id }).$
```
?

2022-05-12 14:16 UTC, kmaid commented on packages/react-components/src/organisms/SpeakersList.tsx
> +                    {user?.displayName}
```suggestion
                    {user.displayName}
```

2022-05-12 14:16 UTC, kmaid commented on packages/validation/src/user-guards.ts
> +  user: EventSpeakerUser | undefined,
Actually i think External speakers are coming later

2022-05-12 14:21 UTC, kmaid commented on packages/validation/src/user-guards.ts
> +): boolean => {
```suggestion
):  user is EventSpeakerUser => {
```

2022-05-12 15:32 UTC, kmaid commented on packages/react-components/src/templates/EventPage.tsx
> +        {props.speakers.length && <SpeakerList {...props} />}
```suggestion
        {!!props.speakers.length && <SpeakerList {...props} />}
```
JSX will print 0 without !!. Sorry

2022-05-12 15:35 UTC, kmaid approved these changes

2022-05-13 12:53 UTC, markcsims approved these changes

2022-05-13 13:53 UTC, merged