feat: adds onnect by code for rules webhook
yldio/asap-hub pull request #167
Opened 2020-08-18 16:08 UTC by johnytiago

2020-08-19 08:46 UTC, fampinheiro approved these changes

2020-08-19 15:06 UTC, jeysal requested changes

2020-08-19 15:06 UTC, jeysal commented on packages/auth0-functions/package.json
> +  "main": "build/index.js",
These do not exist - we can remove the fields or (this is my preference) reduce te app to just this function in an `index.ts`, and when we create another function, just create a different app for it

2020-08-20 11:28 UTC, jeysal approved these changes
will need to extend the auth0.md docs but that can be done later once the new rules are in place and tested :+1:

2020-08-20 11:28 UTC, merged