Crn 933 add sort by oldest event date for past events in calendar events page viii
yldio/asap-hub pull request #1742
Opened 2022-06-29 10:36 UTC by oratiu

2022-06-30 14:50 UTC, kmaid commented on packages/algolia/test/client.test.ts
> +    console.log(response.hits[0]);
This should be thrown by eslint. I think this stage I want the prettier commits taken out of this branch and es lint and its fixed put into the new branch to be merged separately before this

2022-06-30 14:52 UTC, kmaid commented on packages/algolia/test/client.test.ts
> +  test('Should search event entity', async () => {
I think this test title should probally say if its supposed to be in the past or future

2022-06-30 15:00 UTC, peterstarling requested changes

2022-06-30 15:00 UTC, peterstarling commented on packages/algolia/src/client.ts
> +    descending?: boolean,
what if we need another replica for another different sort type? Are these replicas there just so we can search in reverse order? I think other combinations might be required later, maybe we need some sort of map here for sort order? also technically at the moment this replica should only ever be used for events - shouldnt our type or implementation reflect that?

2022-07-01 08:02 UTC, niezgoda commented on schema/algolia-reverse-timestamp-schema.json
> +{
maybe it is worth to put attributesForFaceting and attributesToIndex into one place?

2022-07-05 11:01 UTC, closed without merging