Initial commit of About Asap page
yldio/asap-hub pull request #1882
Opened 2022-08-04 10:21 UTC by kmaid

2022-08-08 14:50 UTC, evemontalvao approved these changes

2022-08-10 07:08 UTC, peterstarling requested changes

2022-08-10 07:08 UTC, peterstarling commented on packages/model/src/discover.ts
> +  membersHref?: string;
I would propose to return an ID of the ASAP team instead
```suggestion
  asapTeamId?: string;
```

2022-08-11 09:40 UTC, kmaid commented on packages/react-components/src/templates/DiscoverAbout.tsx
> +        href: membersTeamId,
This wont work. It needs to use the routing library

2022-08-15 14:12 UTC, merged