feat: CRN-1050 Create Prod/Dev Contentful Apps
yldio/asap-hub pull request #2031
Opened 2022-09-14 13:45 UTC by peterstarling

2022-09-16 08:30 UTC, markcsims requested changes

2022-09-16 08:30 UTC, markcsims commented on .github/workflows/reusable-build.yml
> +        required: true
This isn't used anywhere

2022-09-16 08:30 UTC, markcsims commented on .github/workflows/reusable-deployment.yml
> +          CONTENTFUL_ENVIRONMENT: ${{ inputs.environment-name }}
This is tied to our environment name. branch, development and production. 

Might be better to separate this off into it's own variable

2022-09-16 08:30 UTC, markcsims commented on packages/contentful/.eslintrc.js
> +    'max-classes-per-file': 'off',
Why are we turning these 2 things off?

2022-09-16 08:30 UTC, markcsims commented on packages/contentful/package.json
> +    "schema:import": "contentful space import --content-model-only=true --space-id=$CONTENTFUL_SPACE_ID --environment-id=$CONTENTFUL_ENVIRONMENT --content-file=./schema/schema.json"
Should we start prefixing/suffexing these things with crn/gp2? Even the schema location in the package.

2022-09-16 08:40 UTC, peterstarling commented on .env.example
> +CONTENTFUL_ENVIRONMENT=dev
it's for local development - the command in package.json uses it

2022-09-19 08:28 UTC, peterstarling commented on packages/contentful/package.json
> +    "schema:export:crn": "contentful space export --skip-content=true --space-id=$CONTENTFUL_SPACE_ID --environment-id=$CONTENTFUL_ENVIRONMENT --content-file=./schema/crn-schema.json",
```suggestion
    "space:export:crn": "contentful space export --skip-content=true --space-id=$CONTENTFUL_SPACE_ID --environment-id=$CONTENTFUL_ENVIRONMENT --content-file=./schema/crn-schema.json",
```

2022-09-19 08:28 UTC, peterstarling commented on packages/contentful/package.json
> +    "schema:import:crn": "contentful space import --content-model-only=true --space-id=$CONTENTFUL_SPACE_ID --environment-id=$CONTENTFUL_ENVIRONMENT --content-file=./schema/crn-schema.json",
```suggestion
    "space:import:crn": "contentful space import --content-model-only=true --space-id=$CONTENTFUL_SPACE_ID --environment-id=$CONTENTFUL_ENVIRONMENT --content-file=./schema/crn-schema.json",
```

2022-09-19 08:28 UTC, peterstarling commented on packages/contentful/src/autogenerated-gql/gql.ts
> +/* eslint-disable */
move this file to crn/

2022-09-19 08:28 UTC, peterstarling commented
add documentation

2022-09-19 10:00 UTC, markcsims approved these changes

2022-09-19 11:13 UTC, merged