feat: config and verify squidex webhooks
yldio/asap-hub pull request #210
Opened 2020-09-03 17:07 UTC by johnytiago

2020-09-03 17:23 UTC, johnytiago commented
Your're missing the assignment of the variable here: https://github.com/yldio/asap-hub/blob/master/serverless.js#L58

2020-09-04 08:14 UTC, fampinheiro requested changes

2020-09-04 08:14 UTC, fampinheiro commented on ci/config-squidex-rules.sh
> +  sed -i -E 's#https?\:\/\/(www\.)?[[:alpha:]|.]+#'$API_HOSTNAME'#' @file
```suggestion
  sed -i -E 's#https?\:\/\/(www\.)?[[:alpha:]|.]+#https://$API_HOSTNAME#' @file
```

2020-09-04 09:14 UTC, johnytiago commented
You're a genious @JT you added a function but you didn't even bother to update the tests? 😂

2020-09-04 12:39 UTC, fampinheiro approved these changes

2020-09-04 12:45 UTC, merged