CRN-1095 Inactive badge in events for teams and groups
yldio/asap-hub pull request #2198
Opened 2022-10-20 16:22 UTC by gabiayako

2022-10-24 14:03 UTC, peterstarling requested changes

2022-10-24 14:03 UTC, peterstarling commented on apps/crn-server/test/controllers/events.test.ts
> +              inactiveSince: '2021-10-12T15:42:05Z',
same as above, can you not add this to the fixture?

2022-10-24 14:03 UTC, peterstarling commented on apps/crn-server/test/controllers/events.test.ts
> +                  inactiveSince: '2021-10-12T15:42:05Z',
speaking of testing it individually - what happens when it comes back as null?

2022-10-24 14:51 UTC, gabiayako commented on apps/crn-server/test/controllers/events.test.ts
> +                  inactiveSince: '2021-10-12T15:42:05Z',
I added it now here https://github.com/yldio/asap-hub/pull/2198/commits/9f8fdbdd23e072bd93ce1c6cb71eed5f7b845ee3 :)


The tests I added this `inactiveSince: '2021-10-12T15:42:05Z'` make use of this `getSquidexGraphqlClientMockServer` and it seems that when it comes back as undefined is being replaced by Instant (https://github.com/yldio/asap-hub/blob/CRN-1095-calendar-and-events-inactive-groups-list-and-detail-view/apps/crn-server/test/mocks/squidex-graphql-client-with-server.mock.ts#L41). I'm having trouble to understand where this replacing is coming from though. Is it something from createMockStore?

2022-10-26 09:21 UTC, gabiayako commented on apps/crn-server/src/entities/event.ts
> +      } as EventSpeakerTeam;
yeah! that's right! I didn't notice before that changing the type of display name would give an error without the cast! Thanks!
I removed the casts in here https://github.com/yldio/asap-hub/pull/2198/commits/76dfe3673930db687e64d2ded4bc504894a34648

2022-10-26 15:36 UTC, merged