Initial commit of Recommended users
yldio/asap-hub pull request #2270
Opened 2022-11-14 12:03 UTC by oratiu

2022-11-15 10:45 UTC, kmaid commented on packages/react-components/src/atoms/Ellipsis.tsx
> +  readonly title?: string;
unit test

2022-11-15 10:46 UTC, kmaid commented on packages/react-components/src/organisms/DashboardRecommendedUsers.tsx
> +const DashboardRecommendedUsers: React.FC<DashboardRecommendedUsersProps> = ({
This component doesn't seem to have allot in it. Why was it separated from recommended user? Is that design element reused?

2022-11-15 10:47 UTC, kmaid commented on packages/react-components/src/organisms/RecommendedUser.tsx
> +        noMargin
I wonder if LinkHeadline should have had title set? I think it might already take title

2022-11-15 10:48 UTC, kmaid commented on packages/react-components/src/organisms/RecommendedUser.tsx
> +      <div css={tagListStyles}>
There is already a component called taglist which this seems to be duplicating. What is the functionality difference?

2022-11-15 10:50 UTC, kmaid requested changes
See comments

2022-11-15 14:39 UTC, lctrt commented
needs more tests but looks good to me otherwise :)

2022-11-15 15:14 UTC, kmaid commented on packages/react-components/src/molecules/TagList.tsx
> +        isVertical && verticalList,
Could this match MemberList?

2022-11-16 14:08 UTC, lctrt approved these changes

2022-11-16 14:12 UTC, merged