CRN-1178 add working groups card component
yldio/asap-hub pull request #2396
Opened 2023-01-02 13:49 UTC by lctrt

2023-01-05 11:03 UTC, gabiayako reviewed
I haven't looked at everything yet, just submitting what I've noticed for now 😉 later I will take a look at the rest

2023-01-05 11:03 UTC, gabiayako commented on apps/crn-server/src/data-providers/users.data-provider.ts
> +          role: wgRole || '',
Maybe we don't need this `|| ''` because working group `title` is required and the role is `Member` by default in the reduce above 😉

2023-01-05 13:34 UTC, gabiayako requested changes
looks good, just requesting changes to meet some requirements :)

2023-01-05 13:34 UTC, gabiayako commented on packages/react-components/src/organisms/WorkingGroupsTabbedCard.tsx
> +    <TabbedCard
The requirement of maximum 6 working groups is missing here 😉

2023-01-05 13:34 UTC, gabiayako commented on packages/model/src/working-group.ts
> +  role: string;
maybe this could be

```suggestion
  role: 'Chair' | 'Project Manager' | 'Member';
```

2023-01-06 11:29 UTC, closed without merging

2023-01-06 11:29 UTC, lctrt commented
new PR here: https://github.com/yldio/asap-hub/pull/2409