Chore: Refactor skills list to taglist
yldio/asap-hub pull request #242
Opened 2020-09-14 13:08 UTC by kmaid

2020-09-14 14:43 UTC, jeysal requested changes

2020-09-14 14:43 UTC, jeysal commented on packages/react-components/src/molecules/__tests__/TagList.test.tsx
> +it('shows all skills when there are few', () => {
```suggestion
it('shows all tags when there are few', () => {
```

2020-09-14 14:43 UTC, jeysal commented on packages/react-components/src/molecules/__tests__/TagList.test.tsx
> +it('shows all skills when there are few', () => {
can you also move this into a describe block `when summarized` or so, together with the other test it applies to

2020-09-14 14:43 UTC, jeysal commented on packages/react-components/src/molecules/TagList.tsx
> +const TagList: React.FC<TagListProps> = ({ tags, summarize = false }) =>
It seems you haven't used this in `TeamCard` yet

2020-09-15 09:02 UTC, fampinheiro approved these changes

2020-09-15 09:28 UTC, merged