Crn 153 past team members
yldio/asap-hub pull request #2477
Opened 2023-01-18 12:39 UTC by ricardocarvalh0

2023-01-26 16:56 UTC, kmaid commented on packages/react-context/src/__tests__/auth.test.tsx
> +  useCurrentUserTeamStatusesCRN,
😢 statuses

2023-01-26 16:57 UTC, kmaid approved these changes
I never want to read "Active" again

2023-01-27 09:07 UTC, peterstarling requested changes

2023-01-27 09:07 UTC, peterstarling commented on packages/squidex/schema/crn/schemas/users.json
> +            "name": "inactiveSinceDate",
i wonder if we need both of these fields at the same time?

Let me ask you this - can a user be inactive but not have an `inactiveSinceDate` set? Cause with your current proposal that would be possible, and your types seem to reflect it:
https://github.com/yldio/asap-hub/blob/0eb3e0b6dbf0bcc8d4a3c7e3d174a3d272cd3b19/packages/model/src/user.ts#L109-L110

What is even more strange is that the ticket does not seem to require such field, nor do any of the FE components seem to use it. 

If we know we are going to need such date then I suggest we make sure the requirements are clear. To me - if a user is set to inactive a date will be required, in which case I would be tempted to remove the `status` field and just use the `inactiveSinceDate`. You could leave both of them in the Response type so it's easier for FE to check the status, but the data provider would only return this one.

2023-02-07 07:57 UTC, closed without merging