Update Jest 29.4.0
yldio/asap-hub pull request #2545
Opened 2023-02-02 13:45 UTC by lctrt

2023-02-02 14:52 UTC, kmaid approved these changes

2023-02-03 08:10 UTC, peterstarling approved these changes

2023-02-06 09:48 UTC, peterstarling requested changes

2023-02-06 09:48 UTC, peterstarling commented on apps/crn-server/test/handlers/webhooks/webhook-run-migrations.test.ts
> +      expect(mockUp).toHaveBeenCalledTimes(1);
ok so the goal of the test is not really preserved actually. You see - the point of this test is this:

1. Our read-dir function finds 3 files and they need to be run in sequence
2. The runner should run the first one - it should not error as per this line:
https://github.com/yldio/asap-hub/pull/2545/files#diff-430f88e7bf62e1cd44dc77f7cce896503065c4af36cc1000bec709525bbdc7b9R179
3. Once processed the runner should store the information in the db that the file has been run (see the expectation on the spy below)
4. The runner should then proceed to the next migration by running the mockUp function again and this should fail as per 
https://github.com/yldio/asap-hub/pull/2545/files#diff-430f88e7bf62e1cd44dc77f7cce896503065c4af36cc1000bec709525bbdc7b9R180
5. The runner should exit by throwing but before it should log that the second migration has failed (see expectation at line #191)

Now what I think happens is that the new jest somehow does not preserve the order of rejected and resolved values on the mockUp - it's worth checking if there is a way to tell it to do it in such order.

2023-02-06 09:48 UTC, peterstarling commented on apps/gp2-server/test/handlers/webhooks/webhook-run-migrations.test.ts
> +        expect.stringMatching(/1-test-migration/),
same as in crn (love the duplication btw) - this should not be changed

2023-02-06 09:48 UTC, peterstarling commented on package.json
> +    "test:browser": "yarn test --config=packages/react-components/jest-browser.config.js --passWithNoTests",
if we're removing this from the CI then what do we need this change for?

2023-02-07 16:44 UTC, kmaid commented on apps/gp2-server/package.json
> +    "@types/jest": "27.5.2",
This is wrong

2023-02-08 08:19 UTC, peterstarling approved these changes

2023-02-08 08:20 UTC, merged