GP2 229 refactor event controller
yldio/asap-hub pull request #2676
Opened 2023-02-27 14:02 UTC by markcsims

- refactor event sync to server common
- creates event data provider

2023-02-28 10:02 UTC, peterstarling requested changes

2023-02-28 10:16 UTC, markcsims commented on apps/crn-server/test/controllers/event.test.ts
> +      const result = await eventController.update('7', { description });
yes, agreed. We could raise another ticket to cover this work?

2023-02-28 10:22 UTC, markcsims commented on apps/crn-server/test/controllers/event.test.ts
> +      const result = await eventController.update('7', { description });
yes agreed,

2023-03-01 08:14 UTC, peterstarling approved these changes
i would advise to remove the controller from the handler, i think the controllers are not really a necessary abstraction anyway and their only purpose is to parse data to and from the Response/Input types, but since this google-id method is already exposed in the controller an it's quite handy in our use case i guess we can leave that in for now

2023-03-01 09:15 UTC, merged