[CRN-1298] add relatedResearch field to Research Output
yldio/asap-hub pull request #2753
Opened 2023-03-08 09:42 UTC by ricardocarvalh0

2023-03-08 13:21 UTC, oratiu requested changes
The FE looks good, only thing missing is a story for the new component in Storybook.

2023-03-08 17:32 UTC, gabiayako requested changes
Minor comments, but I am requesting changes to take a second look later :)

2023-03-08 17:32 UTC, gabiayako commented on apps/crn-server/src/entities/research-output.ts
> +  title: flatData?.title || '',
```suggestion
  title: flatData.title || '',
```

2023-03-08 17:32 UTC, gabiayako commented on apps/crn-server/src/entities/research-output.ts
> +  type: researchOutputMapType(flatData?.type) || undefined,
```suggestion
  type: researchOutputMapType(flatData.type) || undefined,
```

2023-03-08 17:32 UTC, gabiayako commented on apps/crn-server/src/entities/research-output.ts
> +    flatData?.documentType &&
```suggestion
    flatData.documentType &&
```

2023-03-08 17:32 UTC, gabiayako commented on packages/model/src/research-output.ts
> +  relatedResearch?: Array<
```suggestion
  relatedResearch: Array<
```

I believe we can remove this `?` as in the parser (https://github.com/yldio/asap-hub/blob/crn-1298-related-research-to-shared-output/apps/crn-server/src/entities/research-output.ts#L67:L70) we guarantee that `relatedResearch` is always returned, right?

2023-03-08 17:32 UTC, gabiayako commented on packages/react-components/src/organisms/ResearchOutputRelatedResearchCard.tsx
> +      description="List all resources that were important to the creation of this output. Only published outputs on the CRN Hub will be available below."
This looks different from figma. Maybe this text "List all ..." should not be part of this `LabeledMultiSelect`, maybe it should be a text above this `LabeledMultiSelect` component and here we wouldn't have a description.
<img width="1440" alt="Screenshot 2023-03-08 at 14 29 50" src="https://user-images.githubusercontent.com/16595804/223786604-05fb3546-4d68-4938-aa93-a414ceb66b63.png">

2023-03-10 13:33 UTC, gabiayako approved these changes

2023-03-10 13:33 UTC, gabiayako commented on packages/react-components/src/molecules/FormCard.tsx
> +  },
is this necessary? 🤔

2023-03-10 13:33 UTC, gabiayako commented on packages/react-components/src/templates/__tests__/ResearchOutputForm.test.tsx
> +    // await waitForElementToBeRemoved(() => screen.queryByText(/loading/i));
Can we remove this comment? :)

2023-03-10 13:33 UTC, gabiayako commented on packages/react-components/src/templates/SharedResearchOutput.tsx
> +        )} */}
was intentional to leave this commented out? I believe this is part of @oratiu task, right?

2023-03-10 15:34 UTC, oratiu approved these changes

2023-03-14 09:32 UTC, closed without merging