Crn 1251 2
yldio/asap-hub pull request #2811
Opened 2023-03-16 14:15 UTC by gabiayako

2023-03-20 15:38 UTC, peterstarling requested changes

2023-03-20 15:38 UTC, peterstarling commented on packages/cms-data-sync/src/migrate-news-and-pages.ts
same as before (and all over the place really) i think we can just drop support for migrations of news and pages.

2023-03-20 17:21 UTC, gabiayako commented on packages/cms-data-sync/src/migrate-news-and-pages.ts
done in this commit [remove news-page migration](https://github.com/yldio/asap-hub/pull/2811/commits/77e1493558f33f898d2a07bbe02e7da5de2ae1a1)

2023-03-20 17:21 UTC, gabiayako commented on .github/workflows/on-demand-cms-sync.yml
> +          - news-and-pages
done in this commit [remove news-page migration](https://github.com/yldio/asap-hub/pull/2811/commits/77e1493558f33f898d2a07bbe02e7da5de2ae1a1)

2023-03-20 17:21 UTC, gabiayako commented on packages/cms-data-sync/test/teams/teams.data-migration.test.ts
> +    jest.resetModules();
yeah, this was not necessary 🙈 
done in this commit: [remove unnecessary reset modules](https://github.com/yldio/asap-hub/pull/2811/commits/9b12f5a56aa3a5067512d9b438527074588e7e67)

2023-03-21 11:38 UTC, peterstarling requested changes

2023-03-21 11:38 UTC, peterstarling commented on packages/cms-data-sync/test/teams/teams.data-migration.test.ts
> +  it('still creates the team even if there is a tool with invalid link', async () => {
can you add another test for when there are 2 tools one of which has an invalid link?

2023-03-21 11:38 UTC, peterstarling commented on packages/cms-data-sync/src/teams/teams.data-migration.ts
> +        logger(`Invalid tool URL linked to team with id: ${id}`, 'ERROR');
there is still one issue with this :D it will reject all links if only one fails, no? i think we wanna be able to insert the valid ones

2023-03-21 13:59 UTC, peterstarling approved these changes

2023-03-21 13:59 UTC, peterstarling commented on packages/cms-data-sync/test/teams/teams.data-migration.test.ts
> +            'en-US': [
if you're adding two tools of which one should fail to parse the URL i think it should only really create one connection here?

2023-03-21 14:11 UTC, gabiayako commented
forced pushed because it was rebased to master

2023-03-21 16:41 UTC, merged