Feat:  Library page
yldio/asap-hub pull request #289
Opened 2020-09-24 16:04 UTC by kmaid

2020-09-25 15:02 UTC, jeysal requested changes

2020-09-25 15:02 UTC, jeysal commented on packages/react-components/src/organisms/__tests__/LibraryCard.test.tsx
> +  const link = getByText('Team A') as HTMLAnchorElement;
```suggestion
  const link = getByText('Team A', { selector: 'a' }) as HTMLAnchorElement;
```
could make it safe I think

2020-09-25 15:02 UTC, jeysal commented on packages/react-components/src/templates/__tests__/LibraryPageHeader.test.tsx
> +  expect((getByRole('textbox') as HTMLInputElement).value).toEqual('test123');
```suggestion
  expect(getByRole('textbox')).toHaveValue('test123');
```

2020-09-25 15:25 UTC, kmaid commented on packages/model/src/research-output.ts
> +  readonly team?: Pick<TeamResponse, 'id' | 'displayName'>;
I copied this from his PR

2020-09-28 10:39 UTC, jeysal approved these changes
LGTM except for weird `TagLabel` styling exception, I hope we can avoid that talking to James? :smile:

2020-09-28 10:39 UTC, jeysal commented on packages/react-components/src/organisms/LibraryCard.tsx
> +const tagStyles = css({ padding: `0 ${2 / perRem}em` });
This came from design QA? Should it not be applied to all `TagLabel`s?

2020-09-28 11:38 UTC, merged