GP2-575 additional news page functionality
yldio/asap-hub pull request #3364
Opened 2023-07-20 10:47 UTC by AkosuaA

2023-08-02 16:16 UTC, markcsims requested changes

2023-08-02 16:16 UTC, markcsims commented on apps/gp2-frontend/src/news/NewsList.tsx
> +  const result = useNews({
```suggestion
  const { items, total } = useNews({
```

2023-08-02 16:16 UTC, markcsims commented on apps/gp2-frontend/src/news/__tests__/state.test.tsx
Do we need to test "state.tsx" - I thought the tests around the News Component should cover this?

2023-08-02 16:16 UTC, markcsims commented on apps/gp2-server/test/data-providers/news.data-provider.test.ts
> +          expect.anything(),
You could possibly replace expect.anything() in this spec with gp2Contentful.FETCH_NEWS -

2023-08-03 11:41 UTC, AkosuaA commented on apps/gp2-frontend/src/news/__tests__/state.test.tsx
There were certain portions that weren't covered. I wasn't sure how to mimic those in the News component tests so I tested them directly

2023-08-04 12:47 UTC, markcsims requested changes

2023-08-04 12:47 UTC, markcsims commented on apps/gp2-frontend/src/news/__tests__/state.test.tsx
> +    await act(() => mockGetNews(options, '').then(setNewsList));
We are executing a mock

Also mixing Promise chains with async...await

2023-08-08 09:47 UTC, markcsims approved these changes

2023-08-08 11:44 UTC, merged