Feat: Pagination
yldio/asap-hub pull request #360
Opened 2020-10-15 15:43 UTC by kmaid

2020-10-16 09:16 UTC, jeysal reviewed
Nice :+1:

2020-10-16 09:16 UTC, jeysal commented on apps/frontend/src/api/__tests__/util.test.tsx
> +    expect(createListApiUrl('test').toString()).toMatch(
come on, don't just go for what requires the least lines changed :see_no_evil: :D
it handles requests without parameters (checks the pathname ends with test as before)
it appends the default pagination params
it selects the given page

2020-10-16 09:16 UTC, jeysal commented on apps/frontend/src/hooks/__tests__/pagination.test.ts
> +  it('Returns provided provided page size', () => {
typo

2020-10-16 09:16 UTC, jeysal commented on apps/frontend/src/hooks/__tests__/pagination.test.ts
> +    expect(renderPageHref(0)).toMatchInlineSnapshot(`"?"`);
This is actually not so nice (browser keeps the `?`), I think `"."` may work in this case? (of course only if no other params are left, search params completely empty)

2020-10-16 09:16 UTC, jeysal commented on apps/frontend/src/hooks/__tests__/pagination.test.ts
> +describe('usePagination', () => {
Only case coming to my mind that is not tested is the one for `numberOfItems === 0`, can we check that the calculation works for that?

2020-10-16 13:59 UTC, fampinheiro approved these changes

2020-10-16 14:32 UTC, jeysal commented
RIP in conflicts. I'm sorry @kmaid, I saw this coming, but had no idea how much it'd be :see_no_evil: 
do you need help resolving? quick call or so

2020-10-19 12:25 UTC, jeysal requested changes
This is blocked on the backend not working correctly yet as if I understand correctly it breaks even existing functionality (showing the first page).
When that is fixed and this is rebased, I'd like to see one tiny test change but looked over it again after the rebase and everything else looks fine :ok_hand:

2020-10-19 12:25 UTC, jeysal commented on apps/frontend/src/api/__tests__/get-list.test.tsx
> +    ).toContain('search=test123');
I think one of the comments was not fully addressed here, can we check this properly using the URL's `searchParams`

2020-10-20 09:50 UTC, jeysal commented
I'd approve, but still gives 400 Bad Request for me :/

2020-10-20 14:34 UTC, johnytiago commented
BE to support this just landed 🎉

2020-10-20 15:01 UTC, merged

2020-10-20 15:01 UTC, jeysal approved these changes