first pass on algolia user search
yldio/asap-hub pull request #3658
Opened 2023-09-07 12:20 UTC by lctrt

2023-09-29 10:18 UTC, gabiayako requested changes

2023-09-29 10:18 UTC, gabiayako commented on apps/gp2-frontend/src/users/UserDirectory.tsx
It seems the export does not work properly when we add a keywords filter because it is still fetching from our BE using `getUsers` and before it was fetching by name of the tag and now it uses the id, so the response comes empty

![before](https://github.com/yldio/asap-hub/assets/16595804/43eddbd7-77e7-488b-85d9-3e5d6e433f93)

![after](https://github.com/yldio/asap-hub/assets/16595804/94fa041f-0d5f-4a1f-a3b4-221a59effced)

2023-10-02 14:35 UTC, markcsims commented on apps/gp2-frontend/src/users/UserDirectory.tsx
It should be using the api to get the users response. Non-onboarded users are not in Algolia. 

The filter wasn't correctly implemented. This is now fixed.

2023-10-02 16:15 UTC, gabiayako approved these changes
Nice! 🎉

2023-10-03 07:57 UTC, merged