logs out entry
yldio/asap-hub pull request #3688
Opened 2023-09-13 10:04 UTC by markcsims

2023-09-21 12:30 UTC, gabiayako approved these changes

2023-09-21 12:30 UTC, gabiayako commented on apps/gp2-server/test/handlers/user/algolia-index-project-handler.test.ts
> +describe('Index Projects on User event handler', () => {
isn't it 
```suggestion
describe('Index Users on Project event handler', () => {
```
?

2023-09-21 12:30 UTC, gabiayako commented on apps/gp2-server/src/handlers/utils.ts
> +      `Found ${found.total} items. Processing ${found.items.length} items.`,
really minor, but maybe we could have 

```suggestion
      `Found ${found.total} items. Processing ${found.items.length} ${type}s.`,
```

and the same thing where we have the other logger info at line 35

2023-09-21 12:35 UTC, peterstarling requested changes
Can you apply this processing function to crn handlers too?

2023-09-22 09:55 UTC, peterstarling approved these changes

2023-09-25 12:11 UTC, merged