Remove sentry DNS for API on Branch Envs
yldio/asap-hub pull request #3914
Opened 2023-11-17 13:43 UTC by kmaid

2023-11-17 15:36 UTC, markcsims approved these changes

2023-11-21 10:10 UTC, peterstarling requested changes

2023-11-21 10:10 UTC, peterstarling commented on apps/crn-server/serverless.ts
> +}
I think you want to do this instead
```suggestion
if (SLS_STAGE === 'dev' || SLS_STAGE === 'production') {
  ['CRN_SENTRY_DSN_API', 'CRN_SENTRY_DSN_HANDLERS'].forEach(env) => {
  assert.ok(process.env[env], `${env} not defined`);
});
}
```
and before the assignment too

2023-11-21 11:20 UTC, peterstarling approved these changes

2023-11-21 11:20 UTC, merged