feat: create staff profile
yldio/asap-hub pull request #413
Opened 2020-10-29 13:32 UTC by fampinheiro

2020-11-03 13:11 UTC, jeysal requested changes

2020-11-03 13:11 UTC, jeysal commented on apps/frontend/src/network/profile/__tests__/Routes.test.tsx
> +        Array [
These kinds of tests are getting a bit out of hand in the FE, the test above you copied this from is quite possibly the worst test in the frontend.
I would suggest having a case for the render condition (that looks for some `'from ASAP'` rendered by `Staff`) and then a test that gets one of the links and checks its href

2020-11-03 13:11 UTC, jeysal commented on apps/storybook/src/ProfilePage.stories.tsx
> +      lastModifiedDate: '1478865224685',
Is this not an ISO 8601 string?

2020-11-04 15:27 UTC, jeysal commented on packages/react-components/src/templates/ProfileHeader.tsx
> +  const teamsProps: ProfileProps['teams'] =
Based on the conversation yesterday, I thought we would solve this by passing the `role` into `ProfilePersonalText` as well and letting it decide what to show for user with role `Staff`

2020-11-05 10:37 UTC, jeysal commented on apps/frontend/src/network/profile/Routes.tsx
>  loadResearch();
@fampinheiro ^ what about this?
Doesn't need testing either, just perf optimization

2020-11-05 10:57 UTC, fampinheiro commented on apps/frontend/src/network/profile/Routes.tsx
>  loadResearch();
I'll create a separate PR for this and improve testing.

2020-11-05 11:28 UTC, johnytiago commented on apps/asap-server/src/entities/user.ts
> +export const parseGraphqlUserTeamConnection = (
Keep it consistent across functions and variables
```suggestion
export const parseGraphQLUserTeamConnection = (
```

2020-11-05 11:29 UTC, johnytiago commented on apps/asap-server/src/entities/user.ts
> +export const parseGraphqlUserTeamConnection = (
Or go the other way around, always lowercase, but we should try to keep it consistent

2020-11-05 12:09 UTC, johnytiago commented on apps/asap-server/src/entities/user.ts
> +      displayName: 'Unknown',
`undefined`?

2020-11-05 12:09 UTC, fampinheiro commented on apps/asap-server/src/entities/user.ts
> +      displayName: 'Unknown',
Not valid.

2020-11-05 12:13 UTC, johnytiago approved these changes

2020-11-05 12:23 UTC, merged