Asap 341 priority crn process and store data for the leadership membership analytics content in algolia
yldio/asap-hub pull request #4204
Opened 2024-03-13 14:08 UTC by gabiayako

2024-03-15 13:16 UTC, gabiayako commented on apps/asap-cli/src/scripts/algolia/set-settings.ts
> +      ...(hasReverseTimestampReplica ? { replicas: [replicaIndexName] } : {}),
I think we won't need the reverse timestamp replica for analytics because we don't want to order teams based on created at or something like that

2024-03-15 14:50 UTC, peterstarling requested changes

2024-03-15 14:50 UTC, peterstarling commented on .github/actions/setup-environment/action.yml
> +            echo "analytics-algolia-index=asap-hub-analytics_CI-$PR_NUMBER" >> $GITHUB_OUTPUT
don't you think it is probably wise to add the app prefix (crn/gp2) already? I can imagine at some point the new requirement might be to introduce analytics to gp2

2024-03-15 14:50 UTC, peterstarling commented on .github/environment/Development
> +analytics-algolia-index=asap-hub-analytics_dev
same here (and probably in many other places in the CI) - add the crn_ prefix

2024-03-15 14:50 UTC, peterstarling commented on .github/workflows/on-remove.yml
> +  analytics-algolia-index:
it feels like a lot of setup just to delete the index and then do it again for the crn-algolia-index one. I'm guessing even the algolia api key you are passing into it has got access to both this one and regular crn-algolia-index so why not just add one line to the the last step of `crn-algolia-index`?

2024-03-15 14:50 UTC, peterstarling commented on .github/workflows/reusable-create-environment.yml
> +          algolia indices copy -y -w $ALGOLIA_INDEX_DEV $ALGOLIA_INDEX
I'm also not sure if we should keeps these two jobs separate... I think creating indexes in general could be done all within one job. The setup is identical right?

2024-03-15 14:50 UTC, peterstarling commented on .github/workflows/reusable-deployment.yml
> +          yarn algolia:set-settings -a $ALGOLIA_APP_ID -k $ALGOLIA_API_KEY -n $ALGOLIA_INDEX -p analytics
same goes for settings - you could just rename ALGOLIA_INDEX to something like ALGOLIA_ENTITY_INDEX and add ALGOLIA_ANALYTICS_INDEX or something like that and have them run step after step

2024-03-15 14:50 UTC, peterstarling commented on apps/asap-cli/src/cli.ts
> +          description: 'Name of App - crn, gp2 or analytics',
what if we have crn and gp2 analytics?

2024-03-19 09:49 UTC, lctrt approved these changes

2024-03-25 09:12 UTC, peterstarling approved these changes

2024-03-25 09:13 UTC, merged