Feat: back button
yldio/asap-hub pull request #532
Opened 2020-12-21 15:36 UTC by kmaid

2021-01-04 10:55 UTC, fampinheiro approved these changes

2021-01-04 15:18 UTC, jeysal requested changes
What are the reasons for doing it this way instead of with explicit back hrefs? What if the user is coming from `about:blank` or so? I think we should discuss the approach for this and similar future cases first

2021-01-05 15:04 UTC, jeysal commented
I've added a comment to reflect that we shouldn't do it like this elsewhere. I'm aware we already have it in the auth frontend, but there it's kind of a different situation because you can get to that page from an infinite number of previous URLs

2021-01-05 15:07 UTC, jeysal approved these changes
I've been overruled on doing this properly, so I guess I approve :D

2021-01-05 15:45 UTC, merged