Feat:  External link component
yldio/asap-hub pull request #534
Opened 2020-12-23 10:39 UTC by kmaid

2021-01-04 10:02 UTC, fampinheiro reviewed
![image](https://user-images.githubusercontent.com/763528/103523338-9bfa2680-4e73-11eb-80d4-421599c72bc7.png)

The text doesn't seem to be centered vertically.

2021-01-04 15:46 UTC, jeysal requested changes

2021-01-04 15:46 UTC, jeysal commented on packages/react-components/src/molecules/ExternalLink.tsx
> +const styles = css({
Can you organise and group these properties a bit? E.g. if `padding` isn't `12 - borderWidth`, nor located close to the border definition, you're not going to remember to adjust the padding if the border width is changed

2021-01-04 15:46 UTC, jeysal commented on packages/react-components/src/molecules/__tests__/ExternalLink.test.tsx
> +});
renders the label
renders an external link icon (which should prompt us to give the icon a proper `<title>`)

2021-01-05 15:48 UTC, jeysal commented on packages/react-components/src/molecules/__tests__/ExternalLink.test.tsx
> +});
:point_up:

2021-01-05 15:48 UTC, jeysal commented on packages/react-components/src/organisms/__tests__/SharedResearchCard.test.tsx
> +  const link = getByText(/external\slink/i, { selector: 'div' }).closest('a');
```suggestion
  const link = getByText(/external\slink/i, { selector: 'a *' }).closest('a');
```
I think, if I understood correctly what's going on

2021-01-07 15:42 UTC, jeysal approved these changes

2021-01-07 15:42 UTC, merged