Feat: Meeting materials
yldio/asap-hub pull request #716
Opened 2021-03-10 11:25 UTC by kmaid

2021-03-10 13:40 UTC, jeysal requested changes
cool mostly lgtm

2021-03-10 13:40 UTC, jeysal commented on apps/storybook/src/AdditionalMaterials.stories.tsx
> +  title: 'Organisms / Additional Materials',
```suggestion
  title: 'Organisms / Events / Additional Materials',
```

2021-03-10 13:40 UTC, jeysal commented on packages/fixtures/src/events.ts
> +    url: '#wrong',
```suggestion
    title: `Material ${i + 1}`,
    url: 'https://example.com/materials/${i}',
```

2021-03-10 13:40 UTC, jeysal commented on packages/react-components/src/organisms/AdditionalMaterials.tsx
> +      <Headline3 styleAsHeading={4}>Additional meeting materials</Headline3>
inconsistent with other parts of the event detail page, which start at heading 2 style as 3 - seems we def need to change the level and you should double check design specs for style

2021-03-10 13:40 UTC, jeysal commented on packages/react-components/src/organisms/__tests__/AdditionalMaterials.test.tsx
> +  expect(queryByRole('heading', { level: 3 })).not.toBeInTheDocument();
```suggestion
  expect(queryByRole('heading')).not.toBeInTheDocument();
```
harder to cause false pass

2021-03-10 13:40 UTC, jeysal commented on packages/react-components/src/organisms/__tests__/AdditionalMaterials.test.tsx
> +  expect(queryByRole('heading', { level: 3 })).not.toBeInTheDocument();
```suggestion
  expect(queryByRole('heading')).not.toBeInTheDocument();
```
harder to cause false pass

2021-03-10 19:28 UTC, jeysal approved these changes

2021-03-11 10:52 UTC, migcarva approved these changes

2021-03-11 11:25 UTC, merged