feat: Updating TextField to support both right and left indicators
yldio/asap-hub pull request #917
Opened 2021-06-17 17:41 UTC by migcarva

2021-06-18 11:57 UTC, kmaid commented on packages/react-components/src/molecules/SearchField.tsx
> +        padding: `${18 / perRem}em 0`,
Please move this out of the component into a css variable

2021-06-18 12:19 UTC, kmaid requested changes

2021-06-18 12:19 UTC, kmaid commented on packages/react-components/src/atoms/TextField.tsx
> +            getIndicatorPadding(getSvgAspectRatio(leftIndicator), 'left'),
I think this could be simplified further. Return the padding string and set it to padding left or right where appropriate

2021-06-18 15:26 UTC, migcarva commented on packages/react-components/src/atoms/TextField.tsx
> +  readonly rightIndicator?: React.ReactElement | null;
Yep, it was from a previous test, thanks :)

2021-06-23 15:54 UTC, kmaid commented on packages/react-components/src/molecules/__tests__/SearchField.test.tsx
> +    const { getByRole } = render(<SearchField placeholder="p" value="q" />);
This test should be improved. You should use rerender. First without a value and ensuring the button isn't present. The second rerender with the value and the button is present

2021-06-23 16:06 UTC, kmaid commented on packages/react-components/src/molecules/__tests__/SearchField.test.tsx
> +      jest.advanceTimersByTime(30 * 1000);
This is brittle. Look for waitFor to solve this

2021-06-23 16:07 UTC, kmaid commented on packages/react-components/src/molecules/__tests__/SearchField.test.tsx
> +      SEARCH_EVENT,
We should not be testing analytics in this test.

2021-06-24 16:47 UTC, kmaid approved these changes

2021-06-29 13:08 UTC, merged