feat: disable nav bar items for not onboarded users with incomplete profile
yldio/asap-hub pull request #961
Opened 2021-07-23 14:59 UTC by ana-yldio

https://trello.com/c/Udf2NtaX/1302-disable-nav-bar-items-for-not-onboarded-users-with-incomplete-profile

2021-07-26 10:06 UTC, kmaid requested changes

2021-07-26 10:57 UTC, migcarva approved these changes
lgtm

2021-07-28 09:24 UTC, jhonny-m approved these changes

2021-07-28 11:38 UTC, kmaid requested changes

2021-07-28 11:38 UTC, kmaid commented on packages/react-components/src/organisms/__tests__/UserNavigation.test.tsx
> +    <UserNavigation {...props} userOnboarded={false} />,
You should put the team within this test. We try to use the generic props to meet the minimum conditions and everything that is asserted on is overwritten within the test to try and avoid changing tests in future.

2021-07-28 11:38 UTC, kmaid commented on packages/react-components/src/organisms/UserNavigation.tsx
> +  readonly userOnboarded: boolean;
This should be optional and default to true

2021-07-28 12:54 UTC, kmaid commented on packages/react-components/src/organisms/__tests__/UserNavigation.test.tsx
> +    <UserNavigation {...props} userOnboarded={false} />,
```suggestion
    <UserNavigation {...props} teams={[{ name: 'Team 1', href: '/team-1' }]} userOnboarded={false} />,
```

2021-07-28 16:54 UTC, closed without merging