feat: add sentry to the frontend
yldio/asap-hub pull request #986
Opened 2021-08-03 14:34 UTC by migcarva

2021-08-06 15:43 UTC, peterstarling requested changes

2021-08-06 15:43 UTC, peterstarling commented on .gitlab-ci.yml
> +    - yarn install --immutable --immutable-cache
just like we said i think its best to move all this into a different job that uses this build artifact, in there you can run yarn install to get the binary you need but i dont think yarn install should be run in the CI before bundling

2021-08-10 09:44 UTC, kmaid commented on .gitlab-ci.yml
> +    - export REACT_APP_RELEASE=$CI_PIPELINE_ID
These are baked into the artifact and have to be done at build

2021-08-10 09:44 UTC, kmaid commented on .gitlab-ci.yml
> +  <<: *tmpl_master
I think this means this will only happen on master

2021-08-10 09:45 UTC, kmaid commented on .gitlab-ci.yml
> +verify:report:frontend:release:
I have done this after a successful dev development at which point its already a release.

2021-08-10 10:12 UTC, peterstarling approved these changes
two minor comments - feel free to address them or not, but what I would say is that I think you should test it and you can do it by simply running the release jump after the sls branch deployment.

2021-08-10 10:12 UTC, peterstarling commented on .gitlab-ci.yml
> +    - build:ts
it doesn't really affect the pipeline but you only really need `deploy:sls:development`

2021-08-10 10:12 UTC, peterstarling commented on apps/frontend/scripts/sentry-release.js
> +createReleaseAndUpload();
i see you are catching the error in the function so i guess there is almost no way for an unhandled promise to occur (unless it fails before line 15). Is that something we really want? Like.. maybe we want to log the error and rethrow, then make sure to exit with non-0 when this happens?

2021-08-10 10:24 UTC, merged